# Generated by Django 5.2.5 on 2025-09-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogues',
            fields=[
                ('код_кат', models.AutoField(db_column='Код кат', primary_key=True, serialize=False)),
                ('каталог', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Каталог', max_length=80, null=True)),
            ],
            options={
                'db_table': 'Каталог',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Complectation',
            fields=[
                ('номер', models.AutoField(db_column='Номер', primary_key=True, serialize=False)),
                ('код', models.CharField(db_collation='Cyrillic_General_CI_AS', db_column='Код', db_comment='код детали по каталогу', max_length=32)),
                ('табл', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Табл', db_comment='таблица по каталогу', max_length=30, null=True)),
                ('поз', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Поз', db_comment='позиция детали по каталогу', max_length=16, null=True)),
                ('наименование', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Наименование', max_length=200, null=True)),
                ('узел', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Узел', max_length=96, null=True)),
                ('усл_заказа', models.BooleanField(blank=True, db_column='Усл заказа', null=True)),
                ('кол', models.FloatField(blank=True, db_column='Кол', null=True)),
                ('ед', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Ед', max_length=14, null=True)),
                ('примечение', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Примечение', max_length=100, null=True)),
                ('дата', models.DateTimeField(blank=True, db_column='Дата', null=True)),
                ('на_складе', models.FloatField(blank=True, db_column='На складе', null=True)),
                ('ssma_timestamp', models.TextField(db_column='SSMA_TimeStamp')),
            ],
            options={
                'db_table': 'Комплектация',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurrentOrders',
            fields=[
                ('код', models.AutoField(db_column='Код', primary_key=True, serialize=False)),
                ('field_текущего_заказа', models.IntegerField(blank=True, db_column='№ТЕКУЩЕГО_ЗАКАЗА', null=True)),
                ('дата', models.DateTimeField(blank=True, db_column='ДАТА', null=True)),
                ('примечание', models.TextField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='ПРИМЕЧАНИЕ', null=True)),
                ('field_заказа', models.IntegerField(blank=True, db_column='№_ЗАКАЗА', null=True)),
                ('статус', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='СТАТУС', max_length=50, null=True)),
                ('у', models.BooleanField(blank=True, db_column='У', null=True)),
                ('ssma_timestamp', models.TextField(db_column='SSMA_TimeStamp')),
            ],
            options={
                'db_table': 'ТЕКУЩИЙ_ЗАКАЗ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentsZip',
            fields=[
                ('код_оборудования', models.AutoField(db_column='Код оборудования', primary_key=True, serialize=False)),
                ('тип', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Тип', max_length=40, null=True)),
                ('наименование', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Наименование', max_length=50, null=True)),
            ],
            options={
                'db_table': 'оборудование',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Firms',
            fields=[
                ('код_фирмы', models.AutoField(db_column='Код фирмы', primary_key=True, serialize=False)),
                ('фирма', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=60, null=True)),
            ],
            options={
                'db_table': 'фирмы',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralIncome',
            fields=[
                ('field_записи', models.AutoField(db_column='№записи', primary_key=True, serialize=False)),
                ('номер', models.IntegerField(blank=True, db_column='Номер', null=True)),
                ('field_заказа', models.IntegerField(blank=True, db_column='№_ЗАКАЗА', null=True)),
                ('кол', models.FloatField(blank=True, db_column='Кол', null=True)),
                ('ед', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Ед', max_length=255, null=True)),
                ('дата_получения', models.DateTimeField(blank=True, db_column='Дата_получения', null=True)),
                ('ssma_timestamp', models.TextField(db_column='SSMA_TimeStamp')),
            ],
            options={
                'db_table': 'Общ_Приход',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralOrders',
            fields=[
                ('field_записи', models.AutoField(db_column='№записи', primary_key=True, serialize=False)),
                ('field_заказа', models.IntegerField(blank=True, db_column='№_ЗАКАЗА', null=True)),
                ('номер', models.IntegerField(blank=True, db_column='Номер', null=True)),
                ('кол', models.FloatField(blank=True, db_column='Кол', null=True)),
                ('ед', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='Ед', max_length=255, null=True)),
                ('усл', models.BooleanField(blank=True, db_column='Усл', null=True)),
                ('дата_заказа', models.DateTimeField(blank=True, db_column='Дата_заказа', null=True)),
                ('ssma_timestamp', models.TextField(db_column='SSMA_TimeStamp')),
            ],
            options={
                'db_table': 'Общ_Заказ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdersZip',
            fields=[
                ('field_field', models.AutoField(db_column='№', primary_key=True, serialize=False)),
                ('заказ_field', models.IntegerField(blank=True, db_column='ЗАКАЗ_№', null=True)),
                ('статус', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='СТАТУС', max_length=50, null=True)),
                ('дата_форм', models.DateTimeField(blank=True, db_column='ДАТА_ФОРМ', null=True)),
                ('дата_подтв', models.DateTimeField(blank=True, db_column='ДАТА_ПОДТВ', null=True)),
                ('сумма_зак', models.DecimalField(blank=True, db_column='СУММА_ЗАК', decimal_places=4, max_digits=19, null=True)),
                ('примечание', models.TextField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='ПРИМЕЧАНИЕ', null=True)),
                ('дата_приход', models.DateTimeField(blank=True, db_column='ДАТА_ПРИХОД', null=True)),
                ('дата_анул', models.DateTimeField(blank=True, db_column='ДАТА_АНУЛ', null=True)),
                ('индекс', models.BooleanField(blank=True, db_column='ИНДЕКС', null=True)),
                ('выполнение', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='ВЫПОЛНЕНИЕ', max_length=50, null=True)),
                ('у', models.BooleanField(blank=True, db_column='У', null=True)),
                ('дата_план_дост', models.DateTimeField(blank=True, db_column='ДАТА_ПЛАН_ДОСТ', null=True)),
                ('ssma_timestamp', models.TextField(db_column='SSMA_TimeStamp')),
            ],
            options={
                'db_table': 'ВЫП_ЗАКАЗОВ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('field_раздел', models.AutoField(db_column='№Раздел', primary_key=True, serialize=False)),
                ('раздел', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='РАЗДЕЛ', max_length=255, null=True)),
            ],
            options={
                'db_table': 'РАЗДЕЛ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
    ]
