# Generated by Django 5.2.5 on 2025-09-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('field_field', models.AutoField(db_column='№', primary_key=True, serialize=False)),
                ('заказ_field', models.IntegerField(blank=True, db_column='ЗАКАЗ_№', null=True)),
                ('статус', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='СТАТУС', max_length=50, null=True)),
                ('дата_форм', models.DateTimeField(blank=True, db_column='ДАТА_ФОРМ', null=True)),
                ('дата_подтв', models.DateTimeField(blank=True, db_column='ДАТА_ПОДТВ', null=True)),
                ('сумма_зак', models.DecimalField(blank=True, db_column='СУММА_ЗАК', decimal_places=4, max_digits=19, null=True)),
                ('примечание', models.TextField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='ПРИМЕЧАНИЕ', null=True)),
                ('дата_приход', models.DateTimeField(blank=True, db_column='ДАТА_ПРИХОД', null=True)),
                ('дата_анул', models.DateTimeField(blank=True, db_column='ДАТА_АНУЛ', null=True)),
                ('индекс', models.BooleanField(blank=True, db_column='ИНДЕКС', null=True)),
                ('выполнение', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', db_column='ВЫПОЛНЕНИЕ', max_length=50, null=True)),
                ('у', models.BooleanField(blank=True, db_column='У', null=True)),
                ('дата_план_дост', models.DateTimeField(blank=True, db_column='ДАТА_ПЛАН_ДОСТ', null=True)),
                ('ssma_timestamp', models.TextField(db_column='SSMA_TimeStamp')),
            ],
            options={
                'db_table': 'ВЫП_ЗАКАЗОВ',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='OrdersZip',
        ),
    ]
