# Generated by Django 4.2 on 2025-06-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production_line_groups',
            fields=[
                ('id', models.SmallIntegerField(db_column='line_group_id', primary_key=True, serialize=False)),
                ('name', models.SmallIntegerField(db_column='group_name')),
                ('decor', models.SmallIntegerField(db_column='is_decor')),
                ('base', models.SmallIntegerField(db_column='is_base')),
                ('order', models.SmallIntegerField(db_column='in_order')),
            ],
            options={
                'db_table': 'c_production_line_group',
                'managed': False,
            },
        ),
    ]
