# Generated by Django 4.2 on 2025-06-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production_lines',
            fields=[
                ('id', models.SmallIntegerField(db_column='production_line_id', primary_key=True, serialize=False)),
                ('name', models.SmallIntegerField(db_column='production_line')),
                ('productivity', models.SmallIntegerField(db_column='productivity')),
                ('internal_number', models.SmallIntegerField(db_column='internal_number')),
                ('report_group_id', models.SmallIntegerField(db_column='report_group_id')),
                ('order', models.SmallIntegerField(db_column='in_order')),
                ('production_section_id', models.SmallIntegerField(db_column='production_section_id')),
                ('summarize_number', models.SmallIntegerField(db_column='summarize_number')),
                ('department_id', models.SmallIntegerField(db_column='department_id')),
            ],
            options={
                'db_table': 'c_production_line',
                'managed': False,
            },
        ),
    ]
