# Generated by Django 4.2 on 2025-06-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0002_production_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snap_types_to_lines',
            fields=[
                ('id', models.SmallIntegerField(db_column='product_id', primary_key=True, serialize=False)),
                ('name', models.SmallIntegerField(db_column='tile_type_id')),
                ('production_line_id', models.SmallIntegerField(db_column='production_line_id')),
                ('productivity', models.SmallIntegerField(db_column='productivity')),
            ],
            options={
                'db_table': 'cu_tile_product',
                'managed': False,
            },
        ),
    ]
