# Generated by Django 4.2 on 2025-06-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0003_snap_types_to_lines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production_line_groups',
            options={'managed': False, 'verbose_name': 'Група виробничої лінії', 'verbose_name_plural': 'Групи виробничих ліній'},
        ),
        migrations.AlterModelOptions(
            name='production_lines',
            options={'managed': False, 'verbose_name': 'Лінія виробництва', 'verbose_name_plural': 'Лінії виробництва'},
        ),
        migrations.AlterModelOptions(
            name='snap_types_to_lines',
            options={'managed': False, 'verbose_name': "Прив'язка до виробничої лінії", 'verbose_name_plural': "Прив'язка до виробничих ліній"},
        ),
    ]
