# Generated by Django 4.2 on 2025-07-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0004_alter_production_line_groups_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSections',
            fields=[
                ('id', models.SmallIntegerField(db_column='production_section_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='production_section', max_length=255)),
                ('order', models.SmallIntegerField(db_column='in_order')),
            ],
            options={
                'verbose_name': 'Секція виробництва',
                'verbose_name_plural': 'Секціі виробництва',
                'db_table': 'c_production_section',
                'managed': False,
            },
        ),
    ]
