# Generated by Django 4.2 on 2025-07-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0005_productionsections'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoppageCauses',
            fields=[
                ('id', models.SmallIntegerField(db_column='stoppage_cause_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='cause', max_length=255)),
            ],
            options={
                'verbose_name': 'Причина простою',
                'verbose_name_plural': 'Причини простою',
                'db_table': 'cu_stoppage_cause',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoppageCausesTypes',
            fields=[
                ('id', models.SmallIntegerField(db_column='stoppage_cause_type_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='cause_name', max_length=255)),
                ('level', models.SmallIntegerField(db_column='level')),
            ],
            options={
                'verbose_name': 'Тип простою',
                'verbose_name_plural': 'Типи простоїв',
                'db_table': 'cu_stoppage_cause_type',
                'managed': False,
            },
        ),
    ]
