# Generated by Django 4.2 on 2025-07-22 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва пункту')),
                ('url_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва URL (reverse name)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('visible', models.BooleanField(default=True, verbose_name='Відображати')),
                ('allowed_roles', models.CharField(blank=True, max_length=255, null=True, verbose_name='SQL-ролі, кому видно (через кому)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.menuitem', verbose_name='Батьківський пункт')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункти меню',
                'db_table': 'navigation_menuitem',
                'ordering': ['order'],
            },
        ),
    ]
