# Generated by Django 4.2 on 2025-06-13 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.SmallIntegerField(db_column='user_id', primary_key=True, serialize=False)),
                ('group_id', models.SmallIntegerField(blank=True, db_column='group_id', null=True)),
                ('system_login', models.CharField(db_column='system_login', max_length=128, unique=True)),
                ('user_name', models.CharField(db_column='user_name', max_length=255)),
                ('subdivision_id', models.SmallIntegerField(db_column='subdivision_id', default=1)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=255, null=True)),
                ('birth_date', models.DateTimeField(blank=True, db_column='birth_date', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False)),
                ('password', models.CharField(db_column='password', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
            ],
            options={
                'db_table': 'c_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorChangeLog',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('design_ean', models.CharField(db_column='design_ean', max_length=50)),
                ('old_author_id', models.SmallIntegerField(db_column='old_author_id')),
                ('new_author_id', models.SmallIntegerField(db_column='new_author_id')),
                ('change_date', models.DateTimeField(auto_now_add=True, db_column='change_date')),
            ],
            options={
                'db_table': 'django_author_change_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserExtras',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'django_user_extras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserSubdivisionHistory',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('subdivision_id', models.SmallIntegerField(db_column='subdivision_id')),
                ('start_date', models.DateTimeField(db_column='start_date')),
                ('end_date', models.DateTimeField(blank=True, db_column='end_date', null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'django_user_subdivision_history',
                'managed': True,
            },
        ),
    ]
