# Generated by Django 4.2 on 2025-06-14 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('system_login', models.CharField(max_length=100, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('subdivision_id', models.IntegerField(default=1)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'c_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserExtras',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'django_user_extras',
                'managed': True,
            },
        ),
    ]
