# Generated by Django 4.2 on 2025-06-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CGroup',
            fields=[
                ('group_id', models.SmallIntegerField(db_column='group_id', primary_key=True, serialize=False)),
                ('group_name', models.CharField(db_column='group_name', max_length=255)),
            ],
            options={
                'db_table': 'c_group',
                'managed': False,
            },
        ),
    ]
