# Generated by Django 4.2 on 2025-06-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
    ]
