# Generated by Django 4.2 on 2025-06-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_cgroup_options_alter_usergroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cgroup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'managed': False},
        ),
    ]
