# Generated by Django 4.2 on 2025-06-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_cgroup_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permition',
            fields=[
                ('permition_id', models.AutoField(db_column='permition_id', primary_key=True, serialize=False)),
                ('permition_value', models.BooleanField(db_column='permition_value', default=False)),
                ('visible', models.BooleanField(db_column='visible', default=False)),
                ('add', models.BooleanField(db_column='add', default=False)),
                ('edit', models.BooleanField(db_column='edit', default=False)),
                ('delete', models.BooleanField(db_column='del', default=False)),
                ('edit_clean_copy', models.BooleanField(db_column='edit_clean_copy', default=False)),
            ],
            options={
                'verbose_name': 'Дозвіл',
                'verbose_name_plural': 'Дозволи',
                'db_table': 'c_permition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermitionObject',
            fields=[
                ('permition_object_name', models.CharField(db_column='permition_object_name', max_length=50, primary_key=True, serialize=False)),
                ('permition_object_caption', models.CharField(blank=True, db_column='permition_object_caption', max_length=255, null=True)),
                ('group_name', models.CharField(blank=True, db_column='group_name', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Об’єкт дозволу',
                'verbose_name_plural': 'Об’єкти дозволів',
                'db_table': 's_permition_object',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='userextras',
            options={'managed': True, 'verbose_name': 'Додаткові дані користувача', 'verbose_name_plural': 'Додаткові дані користувачів'},
        ),
    ]
