# Generated by Django 4.2 on 2025-06-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.SmallIntegerField(db_column='unit_id', primary_key=True, serialize=False)),
                ('name', models.SmallIntegerField(db_column='unit_name')),
                ('unit', models.SmallIntegerField(db_column='unit_alias')),
                ('code', models.SmallIntegerField(db_column='okei')),
                ('id_1c_code', models.SmallIntegerField(db_column='id_1c8')),
            ],
            options={
                'db_table': 'c_unit',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MaterialUnit',
        ),
    ]
