# Generated by Django 4.2 on 2025-06-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_units_delete_materialunit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='units',
            options={'managed': False, 'verbose_name': 'Одиниця виміру', 'verbose_name_plural': 'Одиниці вимірів'},
        ),
    ]
