# Generated by Django 4.2 on 2025-07-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_alter_units_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnits',
            fields=[
                ('product_unit_id', models.SmallIntegerField(db_column='product_unit_id', primary_key=True, serialize=False)),
                ('unit_id', models.SmallIntegerField(db_column='unit_id')),
                ('basic', models.BooleanField(db_column='basic')),
                ('course', models.SmallIntegerField(db_column='course')),
                ('box_unit', models.BooleanField(db_column='box_unit')),
                ('package_unit', models.BooleanField(db_column='package_unit')),
            ],
            options={
                'verbose_name': 'Одиниця виміру продукту',
                'verbose_name_plural': 'Одиниці виміру продукту',
                'db_table': 'cu_product_unit',
                'managed': False,
            },
        ),
    ]
