# Generated by Django 4.2 on 2025-08-16 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_productunits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productunits',
            options={'managed': False, 'verbose_name': 'Одиниця виміру продукту', 'verbose_name_plural': 'Одиниці виміру продуктів'},
        ),
    ]
