# Generated by Django 4.2 on 2025-06-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_structure', '0002_department_sections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department_sections',
            options={'managed': False, 'verbose_name': 'Виробнича секція', 'verbose_name_plural': 'Виробничі секції'},
        ),
    ]
