# Generated by Django 4.2 on 2025-06-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_structure', '0003_alter_department_sections_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subvision',
            fields=[
                ('id', models.SmallIntegerField(db_column='subvision_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='subvision', max_length=255)),
                ('description', models.CharField(blank=True, db_column='descr', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Підрозділ',
                'verbose_name_plural': 'Підрозділи',
                'db_table': 'c_subvision',
                'managed': False,
            },
        ),
    ]
