# Generated by Django 4.2 on 2025-06-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_structure', '0004_subvision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('subdivision_id', models.SmallIntegerField(db_column='subdivision_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='subvision', max_length=255)),
                ('description', models.CharField(blank=True, db_column='descr', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Підрозділ',
                'verbose_name_plural': 'Підрозділи',
                'db_table': 'c_subdivision',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Subvision',
        ),
    ]
