# Generated by Django 4.2 on 2025-07-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_structure', '0005_subdivision_delete_subvision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('shift_id', models.SmallIntegerField(db_column='shift_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='shift', max_length=255)),
                ('shift_foreman', models.CharField(blank=True, db_column='shift_foreman', max_length=255, null=True)),
                ('alias', models.CharField(blank=True, db_column='alias', max_length=255, null=True)),
                ('begin_time', models.TimeField(blank=True, db_column='begin_time', null=True)),
                ('end_time', models.TimeField(blank=True, db_column='end_time', null=True)),
            ],
            options={
                'verbose_name': 'Зміна',
                'verbose_name_plural': 'Зміни',
                'db_table': 'c_shift',
                'managed': False,
            },
        ),
    ]
