# Generated by Django 4.2 on 2025-07-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_structure', '0006_shifts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_types',
            fields=[
                ('store_type_id', models.SmallIntegerField(db_column='store_type_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='store_type', max_length=255)),
            ],
            options={
                'verbose_name': 'Тип складу',
                'verbose_name_plural': 'Типи складів',
                'db_table': 'c_store_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('store_id', models.SmallIntegerField(db_column='store_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='store', max_length=255)),
                ('store_type_id', models.SmallIntegerField(blank=True, db_column='store_type_id', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склади',
                'db_table': 'c_store',
                'managed': False,
            },
        ),
    ]
