# Generated by Django 5.2.5 on 2025-08-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_structure', '0007_store_types_stores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'managed': False, 'verbose_name': 'Цех', 'verbose_name_plural': 'Цехи'},
        ),
        migrations.AlterModelOptions(
            name='subdivision',
            options={'managed': False, 'verbose_name': 'Дільниця', 'verbose_name_plural': 'Дільниці'},
        ),
    ]
