# Generated by Django 4.2 on 2025-06-21 19:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TileType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('box_amount', models.PositiveIntegerField()),
                ('package_amount', models.PositiveIntegerField()),
                ('box_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tolerance', models.DecimalField(decimal_places=2, max_digits=4)),
                ('package_square', models.DecimalField(decimal_places=2, max_digits=6)),
                ('square_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_type_id', models.IntegerField()),
                ('tile_standart_id', models.IntegerField()),
                ('use_modifier', models.BooleanField(default=False)),
                ('combi_design', models.CharField(blank=True, max_length=30, null=True)),
                ('tech_design', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignPassportCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calculated', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_m2', models.PositiveIntegerField()),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passports_designs.design')),
            ],
        ),
        migrations.CreateModel(
            name='DesignMaterialCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('previous_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('changed', models.BooleanField(default=False)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='passports_designs.designpassportcalculation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='passports_designs.material')),
            ],
        ),
        migrations.AddField(
            model_name='design',
            name='tile_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='passports_designs.tiletype'),
        ),
        migrations.CreateModel(
            name='DesignMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_m2', models.DecimalField(decimal_places=3, max_digits=8)),
                ('calculated_amount_per_m2', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('last_calculated', models.DateTimeField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passports_designs.design')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='passports_designs.material')),
            ],
            options={
                'unique_together': {('design', 'material')},
            },
        ),
    ]
