# Generated by Django 5.2.5 on 2025-08-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports_designs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='designmaterial',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='designmaterial',
            index=models.Index(fields=['design', 'material'], name='passports_d_design__491a11_idx'),
        ),
    ]
