# Generated by Django 4.2 on 2025-07-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftReports',
            fields=[
                ('id', models.SmallIntegerField(db_column='doc_id', primary_key=True, serialize=False)),
                ('author_id', models.SmallIntegerField(db_column='author_id')),
                ('doc_date', models.DateTimeField(db_column='doc_date')),
                ('user_id', models.SmallIntegerField(db_column='user_id')),
                ('description', models.TextField(blank=True, db_column='descr', null=True)),
                ('draft', models.BooleanField(db_column='draft', default=False)),
                ('parent_doc_id', models.SmallIntegerField(blank=True, db_column='parent_doc_id', null=True)),
                ('deleted', models.BooleanField(db_column='deleted', default=False)),
                ('read_only', models.BooleanField(db_column='read_only', default=False)),
                ('has_child', models.BooleanField(db_column='has_child', default=False)),
                ('imported', models.BooleanField(db_column='imported', default=False)),
                ('production_line_id', models.SmallIntegerField(blank=True, db_column='production_line_id', null=True)),
                ('shift_id', models.SmallIntegerField(blank=True, db_column='shift_id', null=True)),
                ('stoppage1', models.SmallIntegerField(blank=True, db_column='stoppage1', null=True)),
                ('kiln1', models.SmallIntegerField(blank=True, db_column='kiln1', null=True)),
                ('comments1', models.TextField(blank=True, db_column='comments1', null=True)),
                ('stoppage2', models.SmallIntegerField(blank=True, db_column='stoppage2', null=True)),
                ('kiln2', models.SmallIntegerField(blank=True, db_column='kiln2', null=True)),
                ('comments2', models.TextField(blank=True, db_column='comments2', null=True)),
                ('total', models.SmallIntegerField(blank=True, db_column='total', null=True)),
                ('begin_time', models.TimeField(blank=True, db_column='begin_time', null=True)),
                ('end_time', models.TimeField(blank=True, db_column='end_time', null=True)),
                ('foreman_name', models.CharField(blank=True, db_column='foreman_name', max_length=255, null=True)),
            ],
        ),
    ]
