# Generated by Django 4.2 on 2025-07-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftreports',
            options={'managed': False, 'verbose_name': 'Звіт зміни', 'verbose_name_plural': 'Звіт змін'},
        ),
    ]
