# Generated by Django 4.2 on 2025-07-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_alter_shiftreports_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shiftreports',
            table='d_shift_report',
        ),
    ]
