# Generated by Django 4.2 on 2025-07-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_alter_shiftreports_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftMaterialsDebit',
            fields=[
                ('doc_id', models.SmallIntegerField(db_column='doc_id', primary_key=True, serialize=False)),
                ('doc_number', models.CharField(blank=True, db_column='doc_num', max_length=255, null=True)),
                ('doc_date', models.DateTimeField(db_column='doc_date')),
                ('description', models.TextField(blank=True, db_column='descr', null=True)),
                ('draft', models.BooleanField(db_column='draft', default=False)),
                ('parent_doc_id', models.SmallIntegerField(blank=True, db_column='parent_doc_id', null=True)),
                ('deleted', models.BooleanField(db_column='deleted', default=False)),
                ('read_only', models.BooleanField(db_column='read_only', default=False)),
                ('has_child', models.BooleanField(db_column='has_child', default=False)),
                ('imported', models.BooleanField(db_column='imported', default=False)),
            ],
            options={
                'verbose_name': 'Звіт виробництва по сировині',
                'verbose_name_plural': 'Звіт виробництва по сировині',
                'db_table': 'd_shift_material_debit',
                'managed': False,
            },
        ),
    ]
