# Generated by Django 4.2 on 2025-07-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_shiftmaterialsdebit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftReportRow',
            fields=[
                ('row_id', models.IntegerField(db_column='row_id', primary_key=True, serialize=False)),
                ('is_defect', models.BooleanField(db_column='is_defect', default=False)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=3, max_digits=10)),
                ('unit_id', models.SmallIntegerField(db_column='unit_id')),
                ('box_unit_id', models.SmallIntegerField(db_column='box_unit_id')),
                ('box_amount', models.DecimalField(db_column='box_amount', decimal_places=3, max_digits=10)),
                ('package_amount', models.DecimalField(blank=True, db_column='package_amount', decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'verbose_name': 'Рядок звіту',
                'verbose_name_plural': 'Рядки звіту',
                'db_table': 'dr_shift_report',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='shiftreports',
            options={'managed': False, 'verbose_name': 'Звіт зміни', 'verbose_name_plural': 'Звіти змін'},
        ),
    ]
