# Generated by Django 4.2 on 2025-06-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('design_ean', models.CharField(db_column='design_ean', max_length=50, primary_key=True, serialize=False)),
                ('design_name', models.CharField(blank=True, db_column='design_name', max_length=255, null=True)),
                ('is_test', models.BooleanField(db_column='is_test', default=False)),
                ('tone', models.CharField(blank=True, db_column='tone', max_length=50, null=True)),
                ('quality', models.CharField(blank=True, db_column='quality', max_length=50, null=True)),
                ('height', models.SmallIntegerField(blank=True, db_column='height', null=True)),
                ('width', models.SmallIntegerField(blank=True, db_column='width', null=True)),
                ('thickness', models.DecimalField(blank=True, db_column='thickness', decimal_places=2, max_digits=10, null=True)),
                ('box_amount', models.SmallIntegerField(blank=True, db_column='box_amount', null=True)),
                ('package_amount', models.SmallIntegerField(blank=True, db_column='package_amount', null=True)),
                ('box_weight', models.DecimalField(blank=True, db_column='box_weight', decimal_places=2, max_digits=10, null=True)),
                ('photo', models.BinaryField(blank=True, db_column='photo', max_length='max', null=True)),
                ('tolerance', models.DecimalField(blank=True, db_column='tolerance', decimal_places=2, max_digits=10, null=True)),
                ('package_square', models.DecimalField(blank=True, db_column='package_square', decimal_places=2, max_digits=10, null=True)),
                ('is_base', models.BooleanField(db_column='is_base', default=False)),
                ('tile_1c_id', models.IntegerField(blank=True, db_column='tile_1c_id', null=True)),
                ('parent_ean', models.CharField(blank=True, db_column='parent_ean', max_length=50, null=True)),
                ('print_name', models.CharField(blank=True, db_column='print_name', max_length=255, null=True)),
                ('add_date', models.DateTimeField(blank=True, db_column='add_date', null=True)),
                ('ean', models.CharField(blank=True, db_column='ean', max_length=50, null=True)),
                ('design_code', models.IntegerField(db_column='design_code')),
                ('archived', models.BooleanField(db_column='archived', default=False)),
                ('is_action', models.BooleanField(db_column='is_action', default=False)),
                ('caliber', models.SmallIntegerField(db_column='caliber')),
                ('modifier', models.CharField(blank=True, db_column='modifier', max_length=255, null=True)),
                ('is_stock', models.BooleanField(db_column='is_stock', default=False)),
                ('use_second_color', models.BooleanField(db_column='use_second_color', default=False)),
                ('decor_base_ean', models.CharField(blank=True, db_column='decor_base_ean', max_length=50, null=True)),
                ('set_amount', models.SmallIntegerField(blank=True, db_column='set_amount', null=True)),
                ('amount_in_row', models.SmallIntegerField(blank=True, db_column='amount_in_row', null=True)),
                ('amount_in_column', models.SmallIntegerField(blank=True, db_column='amount_in_column', null=True)),
                ('additional_name', models.CharField(blank=True, db_column='additional_name', max_length=255, null=True)),
                ('laying_type', models.CharField(blank=True, db_column='laying_type', max_length=50, null=True)),
                ('laying', models.CharField(blank=True, db_column='laying', max_length=255, null=True)),
                ('serial_number_in_set', models.SmallIntegerField(blank=True, db_column='serial_number_in_set', null=True)),
                ('amount_panno_in_box', models.SmallIntegerField(blank=True, db_column='amount_panno_in_box', null=True)),
                ('caliber2', models.SmallIntegerField(db_column='caliber2')),
                ('on_tile_ean', models.CharField(blank=True, db_column='on_tile_ean', max_length=50, null=True)),
            ],
            options={
                'db_table': 'c_design',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Tile',
        ),
    ]
