# Generated by Django 4.2 on 2025-06-26 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0002_design_delete_tile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={'managed': False, 'verbose_name': 'Дизайн', 'verbose_name_plural': 'Дизайни'},
        ),
    ]
