# Generated by Django 4.2 on 2025-06-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0003_alter_design_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('quality', models.CharField(db_column='quality', max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='descr', max_length=255, null=True)),
                ('is_defect', models.BooleanField(db_column='is_defect', default=False)),
                ('sort_order', models.SmallIntegerField(blank=True, db_column='sort_order', null=True)),
                ('mark', models.DecimalField(blank=True, db_column='mark', decimal_places=0, max_digits=1, null=True)),
            ],
            options={
                'verbose_name': 'Сорт',
                'verbose_name_plural': 'Сорти',
                'db_table': 'c_quality',
                'managed': False,
            },
        ),
    ]
