# Generated by Django 4.2 on 2025-06-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0004_quality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiletype',
            options={'managed': False, 'verbose_name': 'Тип плитки', 'verbose_name_plural': 'Типи плиток'},
        ),
    ]
