# Generated by Django 4.2 on 2025-06-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0005_alter_tiletype_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tiletype',
            table='tile_type',
        ),
    ]
