# Generated by Django 4.2 on 2025-06-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0006_alter_tiletype_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiletype',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='tiletype',
            table='c_tile_type',
        ),
    ]
