# Generated by Django 4.2 on 2025-06-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0007_alter_tiletype_options_alter_tiletype_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiletype',
            options={'managed': False, 'verbose_name': 'Тип плитки', 'verbose_name_plural': 'Типи плиток'},
        ),
    ]
