# Generated by Django 4.2 on 2025-06-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0008_alter_tiletype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tilestandart',
            fields=[
                ('id', models.SmallIntegerField(db_column='tile_standart_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='standart', max_length=255)),
                ('description', models.CharField(blank=True, db_column='descr', max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, db_column='full_name', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Стандарт плитки',
                'verbose_name_plural': 'Стандарти плиток',
                'db_table': 'cu_tile_standart',
                'managed': False,
            },
        ),
    ]
