# Generated by Django 4.2 on 2025-06-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0009_tilestandart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.SmallIntegerField(db_column='product_group_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='product_group', max_length=255)),
                ('in_order', models.SmallIntegerField(db_column='in_order')),
                ('is_base', models.BooleanField(db_column='is_base', default=False)),
            ],
            options={
                'verbose_name': 'Група продукту',
                'verbose_name_plural': 'Групи продуктів',
                'db_table': 'c_product_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.SmallIntegerField(db_column='product_type_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='product_type', max_length=255)),
                ('short_name', models.CharField(blank=True, db_column='short_name', max_length=255, null=True)),
                ('export_name', models.CharField(blank=True, db_column='export_name', max_length=255, null=True)),
                ('label_name', models.CharField(blank=True, db_column='label_name', max_length=255, null=True)),
                ('use_claiber', models.BooleanField(db_column='use_claiber', default=False)),
            ],
            options={
                'verbose_name': 'Тип продукту',
                'verbose_name_plural': 'Типи продуктів',
                'db_table': 'cu_product_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TilePassportGroup',
            fields=[
                ('id', models.SmallIntegerField(db_column='tile_passport_group_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='tile_passport_group', max_length=255)),
            ],
            options={
                'verbose_name': 'Група плитки для паспорту',
                'verbose_name_plural': 'Групи плиток для паспортів',
                'db_table': 'c_tile_passport_group',
                'managed': False,
            },
        ),
    ]
