# Generated by Django 4.2 on 2025-06-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0010_productgroup_producttype_tilepassportgroup'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producttype',
            table='c_product_type',
        ),
    ]
