# Generated by Django 4.2 on 2025-06-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0011_alter_producttype_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suffix_For_ProductType',
            fields=[
                ('id', models.AutoField(db_column='suffix_for_product_type_id', primary_key=True, serialize=False)),
                ('suffix', models.CharField(db_column='suffix', max_length=255)),
            ],
            options={
                'verbose_name': 'Суфікс для типу продукту',
                'verbose_name_plural': 'Суфікси для типу продукту',
                'db_table': 'c_suffix_for_product_type',
                'managed': False,
            },
        ),
    ]
