# Generated by Django 4.2 on 2025-06-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0012_suffix_for_producttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionGroup',
            fields=[
                ('id', models.SmallIntegerField(db_column='collection_group_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='collection_group', max_length=255)),
                ('description', models.CharField(blank=True, db_column='descr', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Група колекції',
                'verbose_name_plural': 'Групи колекцій',
                'db_table': 'c_collection_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.SmallIntegerField(db_column='collection_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='collection', max_length=255)),
                ('description', models.CharField(blank=True, db_column='descr', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Колекція',
                'verbose_name_plural': 'Колекції',
                'db_table': 'cu_collection',
                'managed': False,
            },
        ),
    ]
