# Generated by Django 4.2 on 2025-07-01 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0014_authors_coats_collectiongroups_colors_decortypes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coats',
            options={'managed': False, 'verbose_name': 'Тип покриття', 'verbose_name_plural': 'Типи покриття'},
        ),
        migrations.AlterModelOptions(
            name='collections',
            options={'managed': False, 'verbose_name': 'Колекція', 'verbose_name_plural': 'Колекції'},
        ),
        migrations.AlterModelOptions(
            name='colors',
            options={'managed': False, 'verbose_name': 'Колір', 'verbose_name_plural': 'Кольори'},
        ),
        migrations.AlterModelOptions(
            name='hues',
            options={'managed': False, 'verbose_name': 'Тон', 'verbose_name_plural': 'Тони'},
        ),
        migrations.AlterModelOptions(
            name='quality',
            options={'managed': False, 'verbose_name': 'Сорт продукції', 'verbose_name_plural': 'Сорти продукції'},
        ),
        migrations.AlterModelOptions(
            name='tilestandarts',
            options={'managed': False, 'verbose_name': 'Стандарт ппродукції', 'verbose_name_plural': 'Стандарти продукції'},
        ),
        migrations.AlterModelOptions(
            name='tiletypes',
            options={'managed': False, 'verbose_name': 'Тип продукції', 'verbose_name_plural': 'Типи продукції'},
        ),
    ]
