# Generated by Django 4.2 on 2025-07-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0015_alter_coats_options_alter_collections_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tilegeometry',
            options={'managed': False, 'verbose_name': 'Геометрія продукту', 'verbose_name_plural': 'Геометрія продуктів'},
        ),
    ]
