# Generated by Django 4.2 on 2025-07-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0016_alter_tilegeometry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaliberTiles',
            fields=[
                ('caliber', models.SmallIntegerField(db_column='caliber', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='descr', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Калібр плитки',
                'verbose_name_plural': 'Калібри плитки',
                'db_table': 'c_caliber_tile',
                'managed': False,
            },
        ),
    ]
