# Generated by Django 4.2 on 2025-07-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0017_calibertiles'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calibertiles',
            table='c_caliber',
        ),
    ]
