# Generated by Django 5.2.5 on 2025-09-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0018_alter_calibertiles_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLabels',
            fields=[
                ('design_label_id', models.SmallIntegerField(db_column='design_label_id', primary_key=True, serialize=False)),
                ('label_name', models.CharField(db_column='label_name', max_length=255)),
                ('file_name', models.CharField(db_column='file_name', max_length=255)),
                ('rows_on_page', models.SmallIntegerField(db_column='rows_on_leaf')),
                ('ean_13', models.BooleanField(db_column='ean_13')),
                ('ean_128', models.BooleanField(db_column='ean_128')),
                ('description', models.CharField(blank=True, db_column='descr', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Етикетка',
                'verbose_name_plural': 'Етикетки',
                'db_table': 'c_design_labels',
                'managed': False,
            },
        ),
    ]
