# Generated by Django 5.2.5 on 2025-09-14 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0019_productlabels'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productlabels',
            table='c_design_label',
        ),
    ]
