# Generated by Django 4.2 on 2025-06-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(db_column='material_id', primary_key=True, serialize=False)),
                ('material_type_id', models.SmallIntegerField(db_column='material_type_id')),
                ('material_kind_id', models.SmallIntegerField(db_column='material_kind_id')),
                ('name', models.CharField(db_column='material', max_length=255)),
                ('fullname', models.CharField(blank=True, db_column='fullname', max_length=500, null=True)),
                ('is_equipment', models.BooleanField(db_column='is_equipment', default=False)),
                ('material_group_id', models.SmallIntegerField(db_column='material_group_id')),
                ('unit_id', models.SmallIntegerField(db_column='unit_id')),
                ('spec', models.CharField(blank=True, db_column='spec', max_length=255, null=True)),
                ('descr', models.TextField(blank=True, db_column='descr', null=True)),
                ('control_param_sample_unit_id', models.SmallIntegerField(blank=True, db_column='control_param_sample_unit_id', null=True)),
                ('archived', models.BooleanField(db_column='archived', default=False)),
                ('humidity', models.DecimalField(blank=True, db_column='humidity', decimal_places=2, max_digits=5, null=True)),
                ('id_1c8', models.CharField(blank=True, db_column='id_1c8', max_length=50, null=True)),
                ('min_rest', models.DecimalField(blank=True, db_column='min_rest', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'cu_material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.SmallIntegerField(db_column='group_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='group', max_length=255)),
            ],
            options={
                'db_table': 'cu_material_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialUnit',
            fields=[
                ('id', models.SmallIntegerField(db_column='unit_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='unit', max_length=100)),
            ],
            options={
                'db_table': 'cu_material_unit',
                'managed': False,
            },
        ),
    ]
