# Generated by Django 4.2 on 2025-06-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialKind',
            fields=[
                ('id', models.SmallIntegerField(db_column='material_kind_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='material_kind', max_length=100)),
            ],
            options={
                'db_table': 'c_material_kind',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.SmallIntegerField(db_column='material_type_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='material_type', max_length=100)),
            ],
            options={
                'db_table': 'cu_material_type',
                'managed': False,
            },
        ),
    ]
