# Generated by Django 4.2 on 2025-06-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_materialkind_materialtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'managed': False, 'verbose_name': 'Матеріал', 'verbose_name_plural': 'Матеріали'},
        ),
        migrations.AlterModelOptions(
            name='materialgroup',
            options={'managed': False, 'verbose_name': 'Група матеріалу', 'verbose_name_plural': 'Групи матеріалів'},
        ),
        migrations.AlterModelOptions(
            name='materialunit',
            options={'managed': False, 'verbose_name': 'Одиниця виміру матеріалу', 'verbose_name_plural': 'Одиниці вимірів матеріалів'},
        ),
    ]
