# Generated by Django 4.2 on 2025-06-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_material_options_alter_materialgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialkind',
            options={'managed': False, 'verbose_name': 'Вид матеріалу', 'verbose_name_plural': 'Види матеріалів'},
        ),
        migrations.AlterModelOptions(
            name='materialtype',
            options={'managed': False, 'verbose_name': 'Тип матеріалу', 'verbose_name_plural': 'Типи матеріалів'},
        ),
    ]
