# Generated by Django 4.2 on 2025-08-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_materialkind_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialGroups',
            fields=[
                ('id', models.SmallIntegerField(db_column='material_group_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='material_group', max_length=255)),
            ],
            options={
                'verbose_name': 'Група матеріалу',
                'verbose_name_plural': 'Групи матеріалів',
                'db_table': 'cu_material_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialKinds',
            fields=[
                ('id', models.SmallIntegerField(db_column='material_kind_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='material_kind', max_length=100)),
            ],
            options={
                'verbose_name': 'Вид матеріалу',
                'verbose_name_plural': 'Види матеріалів',
                'db_table': 'c_material_kind',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(db_column='material_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='material', max_length=255)),
                ('fullname', models.CharField(blank=True, db_column='fullname', max_length=500, null=True)),
                ('is_equipment', models.BooleanField(db_column='is_equipment', default=False)),
                ('spec', models.CharField(blank=True, db_column='spec', max_length=255, null=True)),
                ('descr', models.TextField(blank=True, db_column='descr', null=True)),
                ('control_param_sample_unit_id', models.SmallIntegerField(blank=True, db_column='control_param_sample_unit_id', null=True)),
                ('archived', models.BooleanField(db_column='archived', default=False)),
                ('humidity', models.DecimalField(blank=True, db_column='humidity', decimal_places=2, max_digits=5, null=True)),
                ('id_1c8', models.CharField(blank=True, db_column='id_1c8', max_length=50, null=True)),
                ('min_rest', models.DecimalField(blank=True, db_column='min_rest', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Матеріал',
                'verbose_name_plural': 'Матеріали',
                'db_table': 'cu_material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialTypes',
            fields=[
                ('id', models.SmallIntegerField(db_column='material_type_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='material_type', max_length=100)),
            ],
            options={
                'verbose_name': 'Тип матеріалу',
                'verbose_name_plural': 'Типи матеріалів',
                'db_table': 'cu_material_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialUnits',
            fields=[
                ('id', models.SmallIntegerField(db_column='material_unit_id', primary_key=True, serialize=False)),
                ('basic', models.SmallIntegerField(db_column='basic')),
                ('course', models.SmallIntegerField(db_column='course')),
            ],
            options={
                'verbose_name': 'Одиниця виміру матеріалу',
                'verbose_name_plural': 'Одиниці вимірів матеріалів',
                'db_table': 'cu_material_unit',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='MaterialGroup',
        ),
        migrations.DeleteModel(
            name='MaterialKind',
        ),
        migrations.DeleteModel(
            name='MaterialType',
        ),
        migrations.DeleteModel(
            name='MaterialUnit',
        ),
    ]
