# Generated by Django 4.2 on 2025-08-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_materialgroups_materialkinds_materials_materialtypes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialsTechnnologicalGroups',
            fields=[
                ('id', models.AutoField(db_column='material_teh_group_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='material_teh_group', max_length=255)),
            ],
            options={
                'verbose_name': 'Технологічні група сировини',
                'verbose_name_plural': 'Технологічні групи сировин',
                'db_table': 'c_material_teh_group',
                'managed': False,
            },
        ),
    ]
