# Generated by Django 5.2.5 on 2025-08-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_materialstechnnologicalgroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialsByDepartments',
            fields=[
                ('id', models.AutoField(db_column='material_by_department_id', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Матеріали по дільницях',
                'verbose_name_plural': 'Матеріали по дільницях',
                'db_table': 'cu_material_by_department',
                'managed': False,
            },
        ),
    ]
