# Generated by Django 5.2.5 on 2025-08-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_materialsbydepartments'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='materialsbydepartments',
            table='c_section_material_list',
        ),
    ]
