# Generated by Django 5.2.5 on 2025-08-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_materialsbydepartments_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialsbydepartments',
            options={'verbose_name': 'Матеріал на дільниці', 'verbose_name_plural': 'Матеріали по дільницях'},
        ),
    ]
