# Generated by Django 5.2.5 on 2025-08-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_alter_materialsbydepartments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialsbydepartments',
            options={'managed': False, 'verbose_name': 'Матеріали по дільницях', 'verbose_name_plural': 'Матеріали по дільницях'},
        ),
    ]
