# Generated by Django 4.2 on 2025-06-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.SmallIntegerField(db_column='department_id', primary_key=True, serialize=False)),
                ('name', models.SmallIntegerField(db_column='department')),
                ('use_kiln_press', models.SmallIntegerField(db_column='use_kiln_press')),
            ],
            options={
                'verbose_name': 'Підрозділ',
                'verbose_name_plural': 'Підрозділи',
                'db_table': 'c_department',
                'managed': False,
            },
        ),
    ]
