# Generated by Django 4.2 on 2025-06-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentsTypes',
            fields=[
                ('id', models.SmallIntegerField(db_column='equipment_type_id', primary_key=True, serialize=False)),
                ('name', models.SmallIntegerField(db_column='equipment_type')),
            ],
            options={
                'verbose_name': 'Тип обладнання',
                'verbose_name_plural': 'Типи обладнання',
                'db_table': 'c_equipment_type',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
    ]
