# Generated by Django 4.2 on 2025-07-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_equipmentstypes_delete_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kilns',
            fields=[
                ('kiln_id', models.SmallIntegerField(db_column='kiln_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='kiln', max_length=255)),
                ('production_line_id', models.CharField(blank=True, db_column='production_line_id', max_length=255, null=True)),
                ('hardware_id', models.CharField(blank=True, db_column='hardware_id', max_length=255, null=True)),
                ('kiln_number', models.CharField(blank=True, db_column='kiln_num', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Піч',
                'verbose_name_plural': 'Печі',
                'db_table': 'cu_kiln',
                'managed': False,
            },
        ),
    ]
