# Generated by Django 4.2 on 2025-07-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_kilns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_id', models.CharField(db_column='hardware_id', max_length=255)),
                ('name', models.CharField(db_column='hardware', max_length=255)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('description', models.TextField(blank=True, db_column='descr', null=True)),
            ],
            options={
                'verbose_name': 'Обладнання',
                'verbose_name_plural': 'Обладнання',
                'db_table': 'c_hardware',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hardware_groups',
            fields=[
                ('hardware_group_id', models.SmallIntegerField(db_column='hardware_group_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='hardware_group', max_length=255)),
            ],
            options={
                'verbose_name': 'Група обладнання',
                'verbose_name_plural': 'Групи обладнання',
                'db_table': 'c_hardware_group',
                'managed': False,
            },
        ),
    ]
